version: '3.4'

services:
  samba:
    image: neomediatech/samba-alpine
    environment:
      TZ: 'Europe/Rome'
    networks:
      - default
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    read_only: true
    tmpfs:
      - /tmp
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - /mnt:/mnt:z
    command: '-s "Mount;/mnt"'

networks:
  default:
