# use to create a swarm template in Portainer
version: '3.7'

x-default-opts: 
  &default-opts
  deploy:
    restart_policy:
      condition: on-failure
      delay: 5s
      #max_attempts: 3
      window: 20s

services:
  samba:
    image: neomediatech/samba-alpine
    hostname: samba
    <<: *default-opts
    ports:
      - target: 137
        published: 137
        protocol: udp
        mode: host
      - target: 138
        published: 138
        protocol: udp
        mode: host
      - target: 139
        published: 139
        protocol: tcp
        mode: host
      - target: 445
        published: 445
        protocol: tcp
        mode: host
    #ports:
    #  - "137:137/udp"
    #  - "138:138/udp"
    #  - "139:139/tcp"
    #  - "445:445/tcp"
    volumes:
      - rlst_shares:/data
      - /srv/data/rlst_shares/confs/shares.conf:/shares.conf:ro
    environment:
      TZ: 'Europe/Rome'

volumes:
  rlst_shares:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /srv/data/rlst_shares/files
