# use to create a swarm template in Portainer
version: '3.7'

x-default-opts: 
  &default-opts
  deploy:
    restart_policy:
      condition: on-failure
      delay: 5s
      #max_attempts: 3
      window: 20s

services:
  samba:
    image: neomediatech/samba-alpine
    hostname: samba
    <<: *default-opts
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    volumes:
      - rlst_shares:/mnt
      - /srv/data/rlst_shares/confs/shares.conf:/shares.conf:ro
    environment:
      TZ: 'Europe/Rome'

volumes:
  rlst_shares:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /srv/data/rlst_shares/files
